version: '3'

services:
  # MySQL
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cln_arch
      MYSQL_USER: cln_arch
      MYSQL_PASSWORD: cln_arch
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/conf.d:/etc/mysql/conf.d
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306