definitions:
  outputdata.Auth:
    properties:
      state:
        type: string
    type: object
  outputdata.Callback:
    properties:
      avatorURL:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: 192.168.50.10:8080
info:
  contact: {}
  description: This is a personal project
  license:
    name: takaaki12353491
  title: CLN-ARCH API
  version: "1.0"
paths:
  /oauth:
    post:
      consumes:
      - application/json
      parameters:
      - description: github
        in: query
        name: service
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          schema:
            $ref: '#/definitions/outputdata.Auth'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - OAuth
  /oauth/callback:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputdata.Callback'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - OAuth
swagger: "2.0"
